### List employees
GET http://localhost:8080/employees-web-1.0-SNAPSHOT/api/employees

### Find employee
GET http://localhost:8080/employees-web-1.0-SNAPSHOT/api/employees/1

### Not found
GET http://localhost:8080/employees-web-1.0-SNAPSHOT/api/employees/666

### Create employee
POST http://localhost:8080/employees-web-1.0-SNAPSHOT/api/employees
Content-Type: application/json

{
  "name": "John Doe"
}

### Validation error
POST http://localhost:8080/employees-web-1.0-SNAPSHOT/api/employees
Content-Type: application/json

{
  "name": ""
}

### Update employee
PUT http://localhost:8080/employees-web-1.0-SNAPSHOT/api/employees/1
Content-Type: application/json

{
  "id": 2,
  "name": "John Doe"
}

### Delete
DELETE http://localhost:8080/employees-web-1.0-SNAPSHOT/api/employees/1